title: Word Trees
subtitle: and Other Poems
bookserial: 3-14159265359
page_count: 9

description: Free online publication for interactive visual poetry

author:
  name: Tomer Lichtash
  description: Writer / Developer
  location: Tel-Aviv, Israel
  url: http://tomerlichtash.com/

socialmedia:
  twitter: tomerlichtash
  facebook: tomerlichtash

license:
  symbol: cc
  description: Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License
  url: http://creativecommons.org/licenses/by-nc-sa/4.0/

# Config
source: .
destination: docs

url: 'http://tomerlichtash.com'
baseurl: '/word-trees-and-other-poems'

permalink: /:title/

markdown: kramdown
highlight: rouge
excerpt_separator: "<!--more-->"

# Options: http://jch.penibelst.de
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: false
  ignore:
    envs: [development]

gems:
  - octopress-autoprefixer
  - jekyll-minifier

jekyll-minifier:
  remove_spaces_inside_tags: true
  remove_multi_spaces: true
  remove_comments: true
  remove_quotes: false
  compress_css: true
  compress_javascript: true

exclude:
    - .bundle
    - .sass-cache
    - Gemfile
    - Gemfile.lock
    - package.json
    - assets/scss
    - assets/xslt
    - node_modules
    - npm-debug.log

#msapplication_tileimage: 'msapplication_tileimage.png' # Size 144x144
#msapplication_tilecolor: '#fabb00'

# SEO
google_author: 'https://plus.google.com/103964054247332182133'
google_site_verification: ''
bing_webmastertools_id: '8D3088AFA923B4B07478819F30919DCC'

# Analytics
google_analytics_tracking_id: UA-26201270-10

# Facebook - https://developers.facebook.com/docs/sharing/opengraph/custom#propertytypes
og_image: 'http://tomerlichtash.com/wordtree/assets/img/screenshot.png'
og_locale: 'en_EN'
og_type: 'website'

autoprefixer:
  only_production: false
  browsers:
    - last 2 versions
